# Generated by Django 4.2.5 on 2023-09-23 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_images', '0001_initial'),
        ('user_accounts', '0002_alter_useraccount_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='images',
            field=models.ManyToManyField(related_name='user_accounts', to='user_images.userimage'),
        ),
    ]
