# Generated by Django 4.2.5 on 2023-09-23 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0003_useraccount_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='images',
        ),
    ]
