# Generated by Django 4.2.5 on 2023-09-23 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_images', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userimage',
            name='format',
        ),
        migrations.RemoveField(
            model_name='userimage',
            name='height',
        ),
        migrations.RemoveField(
            model_name='userimage',
            name='width',
        ),
    ]
