# Generated by Django 4.2.5 on 2023-09-23 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_images', '0002_remove_userimage_format_remove_userimage_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='format',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='userimage',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userimage',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
