# Generated by Django 4.2.5 on 2023-09-23 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0004_remove_useraccount_images'),
        ('user_images', '0002_userimage_format_userimage_height_userimage_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='user_accounts.useraccount'),
            preserve_default=False,
        ),
    ]
