# Generated by Django 4.2.5 on 2023-09-23 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0001_initial'),
        ('user_images', '0003_userimage_format_userimage_height_userimage_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='user_accounts.useraccount'),
        ),
    ]
