# Generated by Django 4.2.5 on 2023-09-23 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0001_initial'),
        ('user_images', '0004_alter_userimage_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='user_accounts.useraccount'),
            preserve_default=False,
        ),
    ]
