# Generated by Django 4.2.5 on 2023-09-24 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_images', '0006_alter_userimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='expire_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
