# Generated by Django 4.2.5 on 2023-09-24 23:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_images', '0007_userimage_expire_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='expire_link_duration',
            field=models.PositiveIntegerField(default=300, validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(30000)]),
        ),
    ]
