# Generated by Django 4.2.5 on 2023-09-25 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_images', '0008_userimage_expire_link_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userimage',
            name='expire_link_duration',
        ),
    ]
