# Generated by Django 4.2.5 on 2023-09-25 00:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_images', '0010_remove_userimage_expire_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThumbnailImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('user_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to='user_images.userimage')),
            ],
        ),
        migrations.CreateModel(
            name='ExpireLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expire_link_duration', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(30000)])),
                ('expire_link', models.CharField(max_length=255)),
                ('user_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expire_links', to='user_images.userimage')),
            ],
        ),
    ]
