# Generated by Django 4.2.5 on 2023-09-25 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_images', '0011_thumbnailimage_expirelink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thumbnailimage',
            name='thumbnail',
        ),
    ]
