# Generated by Django 4.2.5 on 2023-09-25 01:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_images', '0012_remove_thumbnailimage_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbnailimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
