# Generated by Django 4.2.5 on 2023-09-25 01:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_images', '0013_thumbnailimage_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnailimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/thumbnails/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='format',
            field=models.CharField(blank=True, editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='height',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='width',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
