# Generated by Django 4.2.5 on 2023-09-25 20:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_images', '0018_alter_userimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='expirelink',
            name='expiration_time',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expirelink',
            name='expire_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='expirelink',
            name='expire_link_duration',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(30000)]),
        ),
    ]
