# Generated by Django 4.2.5 on 2023-09-25 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_images', '0019_expirelink_expiration_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expirelink',
            name='expiration_time',
        ),
    ]
