# Generated by Django 4.2.5 on 2023-09-26 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_images', '0023_expirelink_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expirelink',
            old_name='expire_link',
            new_name='expire_link_token',
        ),
    ]
