# Generated by Django 4.2.5 on 2023-09-27 02:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_images', '0024_rename_expire_link_expirelink_expire_link_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expirelink',
            name='expire_link_duration',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(30000)]),
        ),
    ]
