openapi: 3.0.2
info:
  title: 'ImageTierAPI'
  version: ''
paths:
  /api/images/:
    get:
      operationId: listget_images
      description: 'All images.'
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
                example:
                  - id: 58
                    username: ka_hernes
                    image: /media/images/ELTUN_GASIMOV_f5SWOIi.png
                    format: png
                    width: 630
                    height: 739
                    created_at: '2023-09-26T23:05:46.163167+02:00'
                    user: 3
                  - id: 59
                    username: ka_hernes
                    image: /media/images/ELTUN_GASIMOV_UEU5sPY.png
                    format: png
                    width: 630
                    height: 739
                    created_at: '2023-09-26T23:06:15.419555+02:00'
                    user: 3
                  - id: 60
                    username: gasimovv21
                    image: /media/images/ELTUN_GASIMOV_OJffvTV.png
                    format: png
                    width: 630
                    height: 739
                    created_at: '2023-09-27T00:52:56.397464+02:00'
                    user: 1
                  - id: 61
                    username: gasimovv21
                    image: /media/images/ELTUN_GASIMOV_JXPDZ1o.png
                    format: png
                    width: 630
                    height: 739
                    created_at: '2023-09-27T00:52:57.336057+02:00'
                    user: 1
                  - id: 62
                    username: gasimovv21
                    image: /media/images/ELTUN_GASIMOV_x2t6NQi.png
                    format: png
                    width: 630
                    height: 739
                    created_at: '2023-09-27T00:52:58.151621+02:00'
                    user: 1
                  - id: 63
                    username: gasimovv21
                    image: /media/images/ELTUN_GASIMOV_gBf56F3.png
                    format: png
                    width: 630
                    height: 739
                    created_at: '2023-09-27T00:52:58.845701+02:00'
                    user: 1
                  - id: 64
                    username: gasimovv21
                    image: /media/images/ELTUN_GASIMOV_kYZjw6M.png
                    format: png
                    width: 630
                    height: 739
                    created_at: '2023-09-27T00:52:59.444653+02:00'
                    user: 1
                  - id: 65
                    username: gasimovv21
                    image: /media/images/ELTUN_GASIMOV_cuFFjIO.png
                    format: png
                    width: 630
                    height: 739
                    created_at: '2023-09-27T00:53:00.133224+02:00'
                    user: 1
                  
          description: 'All images.'
      tags:
      - GET All images
  /api/images/{username}/:
    get:
      operationId: retrieveget_user_images
      description: 'User images.'
      parameters:
      - name: username
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
              example:
                 - id: 58
                   username: ka_hernes
                   image: /media/images/ELTUN_GASIMOV_f5SWOIi.png
                   format: png
                   width: 630
                   height: 739
                   created_at: '2023-09-26T23:05:46.163167+02:00'
                   user: 3
                 - id: 59
                   username: ka_hernes
                   image: /media/images/ELTUN_GASIMOV_UEU5sPY.png
                   format: png
                   width: 630
                   height: 739
                   created_at: '2023-09-26T23:06:15.419555+02:00'
                   user: 3
          description: 'The all images of ka_hernes user.'
      tags:
      - GET All user images
  /api/expire-links/{expire_link_token}/:
    get:
      operationId: retrieveget_expire_link
      description: 'User will get the image via the expire_link.'
      parameters:
      - name: expire_link_token
        in: path
        required: true
        description: ''
        schema:
          type: string
          example:
            "example:VF8RSJN9I7bcnT_XCO-BuQ"
      responses:
        '200':
          content:
            application/json:
              schema: {}
              example:
                "IMAGE.PNG/JPG"
          description: ''
      tags:
      - GET Image from expire link
  /api/upload/:
    post:
      operationId: createpost_image
      description: "Add a new image. Users that have 'Basic' plan after uploading an image get: a link to a thumbnail that's 200px in height users that have 'Premium' plan get: a link to a thumbnail that's 200px in height a link to a thumbnail that's 400px in height a link to the originally uploaded image users that have 'Enterprise' plan get a link to a thumbnail that's 200px in height a link to a thumbnail that's 400px in height a link to the originally uploaded image ability to fetch an expiring link to the image (the link expires after a given number of seconds (the user can specify any number between 300 and 30000))"
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: 'Username of the user.'
                tier:
                  type: string
                  description: 'Tier information. Tiers: Basic, Premium, Enterprise'
                image:
                  type: string
                  format: binary
                  description: 'The image file. Allowed formats: PNG/JPG'
                expire_link_duration:
                  type: integer
                  description: 'Duration for link expiration. Required only if tier is "Enterprise".'
              required:
                - username
                - tier
                - image
                - expire_link_duration
      responses:
        '201':
          content:
            application/json:
              schema: {}
              example:
                "Thumbnail 200px": "/media/images\\ELTUN_GASIMOV_UEU5sPY@ka_hernes_thumbnail_200px.png"
                "Thumbnail 400px": "/media/images\\ELTUN_GASIMOV_UEU5sPY@ka_hernes_thumbnail_400px.png"
                "Original Image": "/media/images\\ELTUN_GASIMOV_UEU5sPY.png"
                "Expire Link": "http://127.0.0.1:8000/api/expire-links/VF8RSJN9I7bcnT_XCO-BuQ/"
          description: 'Image uploaded successfully.'
      tags:
      - POST Image